### ISSUE TITLE
k:v can be done via node-redis?

### ISSUE THREAD

**Issue by jbueza** [saem/cacey#2]
redis fun? http://howtonode.org/node-redis-fun

**Comment by saem** [comment]
Yes, it's entirely possible to do this with Redis. As per Harvey's suggestion I'm thinking of just using the file system. The keys will be the file names, and the content in the files.

Then just let the file system/kernel figure everything out.

hasKey -> fstat
get -> cat
etc...

Redis could well be an alternative backend.

The advantage of the file system is that it's SUPER fast, literally blows everything else out of the water. Scaling it is also very straight forward, and backup, etc... are easy as well.

I meant to ask, any objections?
